### ISSUE TITLE
트랜잭션(Transaction)과  트랜잭션 격리 수준

### ISSUE THREAD

**Issue by rimo030** [rimo030/nestjs-e-commerce-frame#25]
재고 수를 줄일 때는 추후 트랜잭션을 고려해야 할 겁니다.
미리 트랜잭션에 대해서 학습해주세요.
DB 트랜잭션에는 4가지 종류가 있습니다.

_Originally posted by @kakasoo in https://github.com/rimo030/Repo-Server/pull/19#discussion_r1382490665_

---

# 📕트랜잭션 
데이터베이스의 상태를 변환시키는 하나의 논리적 기능을 수행하기 위한 작업의 단위 또는 한꺼번에 모두 수행되어야 할 일련의 연산들을 의미. 

- 트랜잭션은 데이터베이스 시스템에서 **병행 제어** 및 **회복 작업** 시 처리되는 작업의 논리적 단위.
- 따라서 하나의 트랜잭션은 Commit 되거나 Rollback된다.

트랜잭션을 쓰는 이유는 데이터의 일관성을 유지하면서 안정적으로 데이터를 복구하기 위함이다.

# 📕트랜잭션 특성 (ACID)

### Atomicity(원자성)
- 트랜잭션의 연산은 DB에 모두 반영되든지 아니면 전혀 반영되지 않아야 한다.
- 완벽히 수행되지 않고 어느 하나라도 오류가 발생하면 트랜잭션 전부가 취소되어야 한다.

### Consistency(일관성)
- 트랜잭션이 실행을 성공적으로 완료하면 언제나 일관성 있는 DB 상태를 유지하는 것.
- 일관성을 깨는 데이터에 대해서는 트랜잭션이 성공적으로 실행되지 않아야 한다는 의미.

### Isolation(독립성)
- 각각의 트랜젝션은 서로 간섭 없이 독립적으로 수행되어야 한다.
- 하나의 트랜잭션 실행 중에 다른 트랜잭션의 연산이 끼어들 수 없다.
-  isolation 성질을 보장할 수 있는 가장 쉬운 방법은 모든 트랜잭션을 순차적으로 수행하는 것이지만,
- 이는 성능을 매우 저하시킨다. 따라서 격리성의 수준을 여러 단계로 나눠놓았다⭐

### 지속성 ( Durability )
- 성공적으로 수행된 트랜잭션은 영원히 반영된다.
- 트랜잭션이 성공했다면, 데이터베이스에 어떤 시스템적인 문제가 발생하더라도 데이터는 영구적으로 보존되어야 함.

# ⭐MySQL의 트랜잭션 격리 수준(Isolation Level)

1. READ UNCOMMITTED
2. READ COMMITTED
3. REPEATABLE READ
4. SERIALIZABLE

### READ UNCOMMITTED
- 커밋하지 않은 데이터 조차도 접근할 수 있는 격리 수준
- 트랜잭션의 작업이 완료되지 않았는데도 다른 트랜잭션에서 볼 수 있는 Dirty Read(오손 읽기)가 발생한다.
- 당연하지만 심각한 정합성 문제가 발생하기 때문에 최소한 READ COMMITTED 이상의 격리 수준을 사용해야한다.

### READ COMMITTED
- 커밋된 데이터만 조회.
- 다른 트랜잭션의 커밋 여부에 따라 조회 결과가 달라지는 Non-Repeatable Read(반복 읽기 불가능)이 발생한다.

### REPEATABLE READ
- 한번 조회한 데이터는 트랜젝션 내에서 다시 조회해도 같은 데이터가 나오는게 보장.
- 하지만 새로운 레코드의 추가 자체를 막는것이 아니기에 유령 읽기(Phantom Read : 결과 집합이 변함)가 발생할 수 있다.

### SERIALIZABLE
- 트랜잭션이 순차적으로 처리되어야 하므로 동시 처리 성능이 매우 떨어진다.
- 여러 트랜잭션이 동일한 레코드에 동시 접근할 수 없으므로, 어떠한 데이터 부정합 문제도 발생하지 않는다. 
- 순수한 SELECT 작업도 대상 레코드에 `Next Key Lock`을 읽기 잠금으로 걸기 때문에, 
- 해당 레코드를 다른 트랜잭션에서는 절대 추가/수정/삭제할 수 없다.

**Comment by rimo030** [comment]
# MySQL 트랜잭션 


### 확인하기
기본값은 `REPEATABLE-READ `이다.
```
SELECT @@GLOBAL.transaction_isolation;
SELECT @@SESSION.transaction_isolation;
```

### 변경하기
```
SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;
```

**Comment by kakasoo** [comment]
트랜잭션 각 단계 별로 어떤 부작용이 있는지 다음에 얘기해봅시다.
사실 글만 봐서는 잘 이해가 안가죠?

**Comment by kakasoo** [comment]
얼마 전에 정리해둔 글입니다. 공유드립니다.

# 5.4. MySQL의 격리 수준

트랜잭션의 격리 수준은 여러 트랜잭션이 동시에 처리될 때,

`특정 트랜잭션이 다른 트랜잭션을 변경하거나 조회하는 데이터를 볼 수 있게 허용할지 여부를 결정한다.`

- READ UNCOMMITED : DIRTY READ 라고도 한다. 일반적으로 사용하지 않는다.
- READ COMITTED
- REPEATABLE READ
- SERIALZABLE : 동시성이 중요하기 때문에 일반적으로 사용하지 않는다.

아래로 갈수록 격리 레벨이 높아지지만 마지막 단계가 아닌 이상에야 크게 차이가 나지는 않는다.

## 5.4.1. READ UNCOMMITED

이름 그대로 `READ UNCOMMITED` 이다.

아직 커밋이 완료되지 않았더라도 읽는 게 가능한 수준의 격리 레벨을 의미한다.

도중에 문제가 생겨 INSERT한 데이터를 ROLLBACK 할지도 모르는 상태에서 해당 레코드 조회가 가능하다.

이를 더티 리드라고도 하며, 더티 리드는 데이터가 나타났다가 사라졌다가 하는 현상을 의미한다.

`RDBMS에서는 더티 리드를 트랜잭션의 격리 수준으로 인정하지 않을 정도로 정합성에 문제가 많다.`

## 5.4.2. READ COMMITED

오라클에서는 기본으로 사용되는 격리 수준이며, 가장 많이 사용되는 격리 레벨이다.

COMMIT이 완료된 이후에만 읽을 수 있게 제한을 걸었다.

- `이전 데이터를 조회할 수 있는 것은 칼럼을 수정할 때, 커밋하지 않았다면 이전 데이터를 언두 로그로 저장해서.`

문제는 트랜잭션이 어떤 데이터를 수정하여 레코드의 특정 칼럼을 변경할 때,

전후로 다른 트랜잭션에 의한 조회가 있을 경우 발생한다.

`예컨대 A를 B로 바꾸고 커밋하기 전 후 다른 트랜잭션 내 조회의 결과는 각각 ‘A’, ‘B’로 조회 결과가 다르다.`

- 트랜잭션 1 시작, 특정 레코드를 조회했을 때 결과가 A
- 트랜잭션 2 시작, 특정 레코드를 수정하여 B로 변경하고 커밋까지 완료
- `아직 종료되지 않은 트랜잭션 1이 다시 특정 레코드 조회 시 결과는 B로 조회된다.`

`즉, 트랜잭션은 자기가 시작할 당시의 정보 값을 유지하고 있어야 하는데, 그렇지 못하다는 것이 문제.`

`이렇게 한 트랜잭션에서 SELECT 쿼리는 동일한 결과를 리턴해야 한다는 것을 REPEATABLE READ 라고 한다.`

**즉, READ COMMITED는 반복적으로 READ 가능한 상태가 아니라는 것.**

## 5.4.3. REPEATABLE READ

MySQL의 InnoDB 스토리지 엔진에서 기본으로 사용되는 격리 수준으로,

`바이너리 로그를 가진 MySQL 서버는 최소 이 단계 이상의 격리 수준을 사용해야 한다.`

언뜻 보기에는 READ COMMITED처럼 보일 수 있지만, 레코드 버전 가운데 이전 버전을 찾아 리턴한다.

모든 InnoDB 트랜잭션은 고유한 트랜잭션 번호 ( 순차적으로 증가하는 값 ) 을 가지며,

언두 영역에 백업된 모든 레코드에는 변경을 발생시킨 트랜잭션 번호를 포함하고 있다.

언두 영역의 백업된 데이터는 InnoDB 스토리지 엔진이 불필요하다고 판단하는 시점에 주기적으로 삭제한다.

REPEATABLE READ 격리 수준에서는 MVCC를 보장하기 위해 실행중인 트랜잭션 가운데,

`가장 오래된 트랜잭션보다 번호가 앞선 언두 영역의 데이터를 삭제하는 것이 불가능하다.`

`더 정확하게는, 특정 트랜잭션 구간 내에서 백업된 언두 데이터들은 모두 보존되어야 한다.`

값이 UPDATE가 일어난 경우에도 정합성을 보장하지만, INSERT 구문에서는 보장하지 못하는 문제가 있다.

```sql
# 언두 영역에서 데이터를 가져올 수 있다고 가정하자.
# 만약 아예 언두 영역에도 없는, 새 데이터가 INSERT된 경우에는?

SELECT WHERE emp_no >= 500000 FOR UPDATE;
```

- 이전의 SELECT 문에서는 이 쿼리가 실행되더라도 데이터가 1개 나왔을 것이다.
- INSERT 이후 트랜잭션이 아직 커밋하지 않았을 때에도 데이터는 정합성이 보장되어야 한다.
- 따라서 데이터는 여전히 1개가 나와야 한다.
- `하지만 다른 트랜잭션에서 2번째 SELECT문을 날린 경우 emp_no가 500000보다 큰 것은 2개다.`
- `이렇게 레코드가 보였다가 안보였다가 하는 것을 팬덤 리드라고 한다.`
    - 더티 리드는 트랜잭션으로 `아직 존재할 수 없는 데이터가 조회되는 것`을 말한다. ( 롤백해야 할 데이터 )
    - 팬텀 리드는 존재할 수 있는 데이터긴 하나 해당 트랜잭션의 시점이 아닌 것을 말한다.

## 5.4.4. SERIALZABLE

가장 단순한 격리 수준이면서 동시에 가장 엄격한 격리 수준이다.

그만큼 동시 처리 성능도 다른 트랜잭션 격리 수준보다 떨어진다.

읽기도 락을 걸어서 다른 트랜잭션이 접근 중인 레코드를 보지 못하게 막아 원천적으로 잘못된 읽기를 차단한다.

`하지만 MySQL은 넥스트 키 락 덕분에 팬덤 리드가 발생하지 않는다.`
