### ISSUE TITLE
npm 명령어들에 대해서 학습하세요.

### ISSUE THREAD

**Issue by rimo030** [rimo030/nestjs-e-commerce-frame#3]
npm 명령어들에 대해서 학습하세요.
여기 있는 `npm run command`들은 package.json의 script를 호출하는 명령어들입니다.

_Originally posted by @kakasoo in https://github.com/rimo030/Repo-Server/pull/1#discussion_r1377329384_

---

# **npm 명령어**

### npm 설치확인

```bash
node -v
npm -v
```

### package.json 생성

```bash
npm init 
npm init -y // 기본값 입력
```

### package 설치

```bash
npm install [패키지명]
npm i [패키지명]
npm i [패키지명@버전이름]
npm i [패키지명] [패키지명2] 

npm i --save [패키지명]    // npm@5부터는 디폴트 
npm i -S [패키지]

npm i --save--dev [패키지명]  // devDependencies로 해당 패키지를 설치
npm i -D [패키지명]

npm install -g [패키지명]
```

### package 삭제

```bash
npm usinstall [패키지명]
npm usinstall -g [패키지명]
```

### package 업데이트

```bash
npm update [패키지명]
```

### start

```bash
npm start 
npm run [script-name]
```

### 그 외

```bash
npm root
npm root -g
npm ls
npm ls --depth=2 
npm ls -g
```

### 전역설치(-g) VS 지역설치

- 전역설치는 시스템상에서 해당 라이브러리의 명령어를 인식하게끔 설정하기 위해 사용한다.
- 프로젝트에서 사용할 라이브러리는 지역설치!

**Comment by kakasoo** [comment]
```bash
npm install package
npm install --save-dev package # 개발종속성
npm install -g package  # 전역 설치이므로 주로 cli나 demon (background program) 등을 설치한다

```

이 세 가지 차이는 아시죠? LGTM

**Comment by rimo030** [comment]
관련 내용을 블로그 글로 작성하였습니다. [[Node.js] npm과 package.json](https://munak.tistory.com/144)
