### ISSUE TITLE
package.json이란?

### ISSUE THREAD

**Issue by rimo030** [rimo030/nestjs-e-commerce-frame#4]
## package.json이란?
`package.json`은 이 프로젝트를 실행하기 위한 최소한의 정보가 담겨져 있습니다.
만약 이 프로젝트가 택배라면 pakcage.json은 박스 위에 붙이는 정보입니다.
누가 만들었고, 열기 위해 무엇이 필요하고, 무엇이 담겨 있고 등등에 대한 정보가 담겨져 있습니다.

_Originally posted by @kakasoo in https://github.com/rimo030/Repo-Server/pull/1#discussion_r1377320802_

---

# package.json
프로젝트에 대한 정보를 가지고 있는 파일. dependecies 와 같은 속성을 활용하여 프로젝트에 의존된 라이브러리를 관리한다.

# 주요 속성 모음

### name

프로젝트(패키지)의 이름. npm 레지스트리에 배포할 경우 사용될 패키지의 이름

### version

프로젝트의 버전 명시

### repository

소스 코드가 저장된 리포지터리의 주소를 명시

### author

개발자 정보

### **description**

문자열로 기술한 패키지에 대한 설명. npm에서 검색되었을 때 리스트에 표시되어 사람들이 패키지를 찾아내고 이해할 수 있는데 도움을 준다.

### main

패키지를 설치하는 곳에서 진입점으로 사용할 파일

만약 index.js를 main 속성에 정의하여 npm 레지스트리에 배포한다면, 해당 패키지를 설치하여 사용하는 프로젝트에서는 자동으로 index.js를 진입점으로 가져와 사용

### files

files 속성이 정의되어 있다면 해당 속성에 정의된 파일들만 배포되고 나머지는 배포되지 않음

### types

타입스크립트를 사용한다면 types 속성에 타입 정의 파일을 명시

### scripts

직접 커스텀 명령어를 정의하여 실행할 수 있다. npm run 명령어로 정의된 명령어를 실행

### dependencies

프로젝트의 의존성 패키지들을 정의하며, 해당 패키지들은 실제 프로덕션 배포에서도 필요한 패키지

### devDependencies

실제 프로덕션 배포에서는 필요하지 않고 개발에만 필요한 패키지들이 정의

# package-lock.json

프로젝트에 설치된 모듈들의 의존성 트리를 기록한다. 이를 참고하여 `node_modules` 디렉토리안에 모듈을 다운받을수 있게 됨

**Comment by kakasoo** [comment]
> types
타입스크립트를 사용한다면 types 속성에 '다'입 정의 파일을 명시

-  오타

**Comment by kakasoo** [comment]
LGTM

**Comment by rimo030** [comment]
관련 내용을 블로그 글로 정리하였습니다¡ [[Node.js] npm과 package.json](https://munak.tistory.com/144)
