### ISSUE TITLE
함수형 프로그래밍 (Functional Programming)

### ISSUE THREAD

**Issue by kakasoo** [rimo030/nestjs-e-commerce-frame#49]
```typescript
new Array(100)
    .fill(0)
    .map((el, i) => i + 1)
    .filter((el) => el % 3 === 0)
    .reduce((acc, cur) => acc + cur, 0);
```

1부터 100까지 3의 배수만 꺼내서 모두 더하는 코드.
함수형은 일단 `return this`를 사용하는 메서드들을 호출한다고 생각하고 작업해도 절반은 됩니다.
추후에는 이터레이터와 이터러블 (Iterator, Iterable) ,제너레이터 (Generator) 등의 개념을 배우게 될 텐데요...
#11 와 이어지는 주제입니다.

**Comment by kakasoo** [comment]
```typescript
const add = (acc, cur) => acc + cur;
const filtering = (n) => (el) => el % n === 0;

new Array(100)
    .fill(0)
    .map((el, i) => i + 1)
    .filter(filtering(3))
    .reduce(add, 0);

```

**Comment by kakasoo** [comment]
```typescript
const makeAdd = (N) => (a) => add(a, N);
const add1 = makeAdd(1);
const add2 = makeAdd(2);
const add3 = makeAdd(3);

```
함수를 값으로서 다루는 건 리턴 타입으로 다루는 것도 포함합니다. 만약 장바구니 같은 걸 구현한다고 한다면, 약간의 조건만 다를 뿐 장바구니와 판매자, 주문서 등에 다 똑같은 수식을 구현해야 하는데, 함수를 값으로 다룰 줄 아는 게 훨씬 유리할 겁니다.

**Comment by kakasoo** [comment]
당장 익히면 좋은 거는 "고차함수", "일급함수", "커링" 정도면 됩니다.

**Comment by rimo030** [comment]
## 일급 객체(First-Class Citizen)
- 함수를 변수에 할당하거나, 인수로 함수를 전달할 수 있다. 
- 즉 함수를 값처럼 다룰 수 있다.

```ts
// 1급 객체
const addTwo = (num) => num + 2;
const multiplyTwo = (num) => num * 2;
const transform = (numbers) => numbers.map(addTwo).map(multiplyTwo);

console.log(transform([1, 2, 3, 4])); // [6, 8, 10, 12]
```

## 고차 함수(Higher-Order Function)
- 함수를 인자로써 전달 할 수 있어야 한다.  (콜백 함수)
- 함수의 반환 값으로 또 다른 함수를 사용 할 수 있다. (커링)
```ts
// 고차 함수
const addInform = (name) => (age) => age + name;
const jongmin = addInform("rimo");

console.log(jongmin("23")); // 23rimo
```

**Comment by kakasoo** [comment]
제가 함수형 프로그래밍 공부한 내용을 정리한 겁니다. 인프런에 있는 함수형 프로그래밍 ( 유인동님 강좌 ) 를 보고 공부한 건데요, 중요한 내용을 요약 정리한 거니까 참고해주세요.

- [함수형 프로그래밍 (Functional Programing)](https://www.notion.so/kakasoo/with-JS-99b69081e3fe49ad964341edc7141068)

**Comment by rimo030** [comment]
관련 내용을 블로그 글로 정리했습니다.
