### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by rimo030** [rimo030/nestjs-e-commerce-frame#5]
## .gitignore

`.gitignore` 파일에는 `git add`가 되지 않게 파일을 필터링할 목록을 기록해둡니다.
가장 대표적으로는 아래 두 가지가 있습니다.

- `/node_modules` : 이미 기록되어 있습니다.
- `/.env` : 사용자가 직접 넣어주어야 합니다.

추후 `.env` 라는 파일에 데이터베이스 암호를 포함한 기타 환경변수들을 모두 기록하게 될 텐데요, 미리 넣어두시는 걸 추천합니다.
이런 암호들을 노출하게 된다면 public한 repository는 해킹 위험이 있습니다.

_Originally posted by @kakasoo in https://github.com/rimo030/Repo-Server/pull/1#discussion_r1377327048_

---

# .gitignore

.gitignore 파일에 다음 줄을 추가함으로써 특정 폴더의 있는 전체파일을 무시할 수 있다.

```bash
[폴더이름]/
```

다음 줄을 추가함으로써 특정 폴더의 있는 전체파일을 무시할 수 있다.

```bash
*.[확장자]/
```

이미 Staging Area나 Respository에 커밋으로 올라간 경우 올라간 파일을 제거해야 한다. 

```bash
git rm [제거할 파일명]
git commit -m "메시지"
```

## gitignore.io
[gitignore.io](http://gitignore.io/)는 언어, OS 나 Framework, IDE 별로 저장소에 추가되면 안 되는 파일과 폴더 목록인 .gitignore 를 자동으로 생성해 주는 서비스이다.

**Comment by kakasoo** [comment]
LGTM

**Comment by rimo030** [comment]
https://munak.tistory.com/146
